import { FeedItem } from '../models';

export const MOCK_FEED: FeedItem[] = [
  {
    id: 'f1',
    type: 'new-experience',
    user: { id: 'u3', displayName: 'Marina Sato', username: 'marinasato', avatarUrl: 'https://picsum.photos/seed/marina-sato/200/200', friendshipStatus: 'friends' },
    createdAt: '2026-09-16T19:00:00.000Z',
    experienceId: 'ext-1',
    dishName: 'Unagi don',
    restaurantName: 'Edomae Kissa',
    city: 'São Paulo',
    rating: 5,
    photoUrl: 'https://picsum.photos/seed/unagi-don/640/420',
    text: 'Enguia grelhada na perfeição, com um molho tare equilibrado.',
    likesCount: 14,
    likedByMe: true,
    comments: [
      { id: 'cm1', userId: 'u2', userDisplayName: 'Rafael Andrade', userAvatarUrl: 'https://picsum.photos/seed/rafael-andrade/200/200', text: 'Preciso ir nesse lugar!', createdAt: '2026-09-16T19:20:00.000Z' },
    ],
  },
  {
    id: 'f2',
    type: 'retrospective-shared',
    user: { id: 'u5', displayName: 'Helena Cortez', username: 'helenacortez', avatarUrl: 'https://picsum.photos/seed/helena-cortez/200/200', friendshipStatus: 'friends' },
    createdAt: '2026-09-14T09:10:00.000Z',
    text: 'Minha retrospectiva de 2025 ficou pronta — 55 experiências e um Top 3 surpreendente!',
    likesCount: 22,
    likedByMe: false,
    comments: [],
  },
  {
    id: 'f3',
    type: 'new-favorite',
    user: { id: 'u2', displayName: 'Rafael Andrade', username: 'rafaeleats', avatarUrl: 'https://picsum.photos/seed/rafael-andrade/200/200', friendshipStatus: 'friends' },
    createdAt: '2026-09-12T21:40:00.000Z',
    dishName: 'Tagliatelle al ragù',
    restaurantName: 'Osteria Bordô',
    city: 'São Paulo',
    photoUrl: 'https://picsum.photos/seed/tagliatelle-ragu/640/420',
    likesCount: 9,
    likedByMe: false,
    comments: [],
  },
  {
    id: 'f4',
    type: 'new-collection',
    user: { id: 'u3', displayName: 'Marina Sato', username: 'marinasato', avatarUrl: 'https://picsum.photos/seed/marina-sato/200/200', friendshipStatus: 'friends' },
    createdAt: '2026-09-08T14:00:00.000Z',
    collectionName: 'Cafés de especialidade em Tóquio',
    text: 'Reuni os melhores cafés que visitei na minha última viagem.',
    likesCount: 17,
    likedByMe: true,
    comments: [
      { id: 'cm2', userId: 'u1', userDisplayName: 'Clara Marques', userAvatarUrl: 'https://picsum.photos/seed/clara-marques/200/200', text: 'Salvando para minha próxima viagem!', createdAt: '2026-09-08T15:00:00.000Z' },
    ],
  },
  {
    id: 'f5',
    type: 'new-experience',
    user: { id: 'u4', displayName: 'Diego Fontenele', username: 'diegofont', avatarUrl: 'https://picsum.photos/seed/diego-fontenele/200/200', friendshipStatus: 'pending-received' },
    createdAt: '2026-09-05T22:15:00.000Z',
    experienceId: 'ext-2',
    dishName: 'Coxinha de rabada',
    restaurantName: 'Boteco do Zé',
    city: 'Rio de Janeiro',
    rating: 4,
    photoUrl: 'https://picsum.photos/seed/coxinha-rabada/640/420',
    likesCount: 6,
    likedByMe: false,
    comments: [],
  },
];
