import { Restaurant } from '../models';

// Dados de demonstração. Nomes e imagens são fictícios e não
// representam estabelecimentos reais.
export const MOCK_RESTAURANTS: Restaurant[] = [
  {
    id: 'r1',
    name: 'Osteria Bordô',
    city: 'São Paulo',
    country: 'Brasil',
    address: 'Rua Harmonia, 421 — Vila Madalena',
    cuisineTypes: ['Italiana'],
    imageUrl: 'https://picsum.photos/seed/osteria-bordo/640/420',
    description: 'Massas artesanais e um ambiente intimista no coração da Vila Madalena.',
    source: 'demo-database',
  },
  {
    id: 'r2',
    name: 'Sakura Nomiya',
    city: 'São Paulo',
    country: 'Brasil',
    address: 'Rua Tomas Gonzaga, 88 — Liberdade',
    cuisineTypes: ['Japonesa'],
    imageUrl: 'https://picsum.photos/seed/sakura-nomiya/640/420',
    description: 'Izakaya tradicional com balcão de sushi ao vivo.',
    source: 'demo-database',
  },
  {
    id: 'r3',
    name: 'Marché Provençal',
    city: 'Paris',
    country: 'França',
    address: '12 Rue des Rosiers',
    cuisineTypes: ['Francesa'],
    imageUrl: 'https://picsum.photos/seed/marche-provencal/640/420',
    description: 'Bistrô clássico parisiense com cardápio sazonal.',
    source: 'demo-database',
  },
  {
    id: 'r4',
    name: 'Casa Azulejo',
    city: 'Lisboa',
    country: 'Portugal',
    address: 'Rua do Alecrim, 15',
    cuisineTypes: ['Mediterrânea'],
    imageUrl: 'https://picsum.photos/seed/casa-azulejo/640/420',
    description: 'Petiscos e vinhos portugueses num salão revestido de azulejos.',
    source: 'demo-database',
  },
  {
    id: 'r5',
    name: 'Kōhī Tōkyō',
    city: 'Tóquio',
    country: 'Japão',
    address: '3-21 Shibuya',
    cuisineTypes: ['Japonesa'],
    imageUrl: 'https://picsum.photos/seed/kohi-tokyo/640/420',
    description: 'Kissaten de especialidade com torra artesanal.',
    source: 'demo-database',
  },
  {
    id: 'r6',
    name: 'Cantina Nonna Rosa',
    city: 'Roma',
    country: 'Itália',
    address: 'Via dei Cappellari, 62',
    cuisineTypes: ['Italiana'],
    imageUrl: 'https://picsum.photos/seed/nonna-rosa/640/420',
    description: 'Trattoria familiar a poucos passos do Campo de\' Fiori.',
    source: 'demo-database',
  },
  {
    id: 'r7',
    name: 'Souk Al Zaatar',
    city: 'São Paulo',
    country: 'Brasil',
    address: 'Rua Bela Cintra, 1230',
    cuisineTypes: ['Árabe'],
    imageUrl: 'https://picsum.photos/seed/souk-zaatar/640/420',
    description: 'Mezze e assados em ambiente aconchegante e especiarias marcantes.',
    source: 'demo-database',
  },
  {
    id: 'r8',
    name: 'Little Saigon Corner',
    city: 'Nova York',
    country: 'Estados Unidos',
    address: '212 Mulberry St',
    cuisineTypes: ['Outras'],
    imageUrl: 'https://picsum.photos/seed/little-saigon/640/420',
    description: 'Pho e banh mi em um cantinho despretensioso do Village.',
    source: 'demo-database',
  },
  {
    id: 'r9',
    name: 'Especiaria de Kerala',
    city: 'Rio de Janeiro',
    country: 'Brasil',
    address: 'Rua Dias Ferreira, 45 — Leblon',
    cuisineTypes: ['Indiana'],
    imageUrl: 'https://picsum.photos/seed/especiaria-kerala/640/420',
    description: 'Curries e pães naan feitos em forno tandoor tradicional.',
    source: 'demo-database',
  },
  {
    id: 'r10',
    name: 'Gyeongju Table',
    city: 'São Paulo',
    country: 'Brasil',
    address: 'Rua Galvão Bueno, 393 — Liberdade',
    cuisineTypes: ['Coreana'],
    imageUrl: 'https://picsum.photos/seed/gyeongju-table/640/420',
    description: 'Churrasco coreano à mesa com acompanhamentos fermentados.',
    source: 'demo-database',
  },
  {
    id: 'r11',
    name: 'Taquería Flor de Milpa',
    city: 'Cidade do México',
    country: 'México',
    address: 'Calle Regina 88',
    cuisineTypes: ['Mexicana'],
    imageUrl: 'https://picsum.photos/seed/flor-de-milpa/640/420',
    description: 'Tacos ao pastor e mezcal em um mercado coberto.',
    source: 'demo-database',
  },
  {
    id: 'r12',
    name: 'Confeitaria Bordeaux',
    city: 'São Paulo',
    country: 'Brasil',
    address: 'Alameda Lorena, 800 — Jardins',
    cuisineTypes: ['Francesa'],
    imageUrl: 'https://picsum.photos/seed/confeitaria-bordeaux/640/420',
    description: 'Confeitaria fina especializada em sobremesas autorais.',
    source: 'demo-database',
  },
];
