import { User } from '../models';

export const CURRENT_USER_ID = 'u1';

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    displayName: 'Clara Marques',
    username: 'claramarques',
    email: 'clara@example.com',
    avatarUrl: 'https://picsum.photos/seed/clara-marques/200/200',
    bio: 'Colecionando sabores pelo mundo, um prato de cada vez.',
    createdAt: '2024-02-10T12:00:00.000Z',
    profileVisibility: 'public',
    stats: { totalExperiences: 0, totalRestaurants: 0, totalCities: 0, totalFavorites: 0, averageRating: 0 },
  },
  {
    id: 'u2',
    displayName: 'Rafael Andrade',
    username: 'rafaeleats',
    email: 'rafael@example.com',
    avatarUrl: 'https://picsum.photos/seed/rafael-andrade/200/200',
    bio: 'Amante de massas e vinhos naturais.',
    createdAt: '2024-03-02T12:00:00.000Z',
    profileVisibility: 'public',
    stats: { totalExperiences: 41, totalRestaurants: 30, totalCities: 6, totalFavorites: 12, averageRating: 4.3 },
  },
  {
    id: 'u3',
    displayName: 'Marina Sato',
    username: 'marinasato',
    email: 'marina@example.com',
    avatarUrl: 'https://picsum.photos/seed/marina-sato/200/200',
    bio: 'Sushi, café de especialidade e viagens gastronômicas.',
    createdAt: '2024-01-18T12:00:00.000Z',
    profileVisibility: 'public',
    stats: { totalExperiences: 67, totalRestaurants: 52, totalCities: 9, totalFavorites: 20, averageRating: 4.6 },
  },
  {
    id: 'u4',
    displayName: 'Diego Fontenele',
    username: 'diegofont',
    email: 'diego@example.com',
    avatarUrl: 'https://picsum.photos/seed/diego-fontenele/200/200',
    bio: 'Sempre em busca do melhor boteco da cidade.',
    createdAt: '2024-05-27T12:00:00.000Z',
    profileVisibility: 'private',
    stats: { totalExperiences: 22, totalRestaurants: 19, totalCities: 3, totalFavorites: 7, averageRating: 4.1 },
  },
  {
    id: 'u5',
    displayName: 'Helena Cortez',
    username: 'helenacortez',
    email: 'helena@example.com',
    avatarUrl: 'https://picsum.photos/seed/helena-cortez/200/200',
    bio: 'Doces, cafés e retrospectivas de fim de ano são meu forte.',
    createdAt: '2024-04-11T12:00:00.000Z',
    profileVisibility: 'public',
    stats: { totalExperiences: 55, totalRestaurants: 41, totalCities: 7, totalFavorites: 18, averageRating: 4.5 },
  },
];
